Add Dormant Microsoft Defender
gdeliana/Optimize-Offline pull request #13
Opened 2022-01-13 02:39 UTC by espanafly

Purpose described in "About Dormant Microsoft Defender" section of "README.md"

2022-01-14 21:56 UTC, gdeliana requested changes
Overall i like the idea. I just had one small question. What happens if the user decides to remove the SecHealthUIPackage and at the same time choses DormantDefender option to ON? Shall we maybe make also a condition in the app/sysapp removal code for not letting the package getting removed even when the user has selected it for removal when he enabled the DormantDefender option?

2022-01-14 21:56 UTC, gdeliana commented on Src/Offline-Resources.psm1
> +$OptimizeOffline.DormantDefender = (Resolve-FullPath -Path $OptimizeOffline.Packages -Child DormantDefender)
Can you please explain me what shall the Packages/DormantDefender folder server for?

2022-01-14 21:56 UTC, gdeliana commented on en-US/Optimize-Offline-help.xml
> +        <dev:code>Optimize-Offline -SourcePath "D:\Images\Windows 10 1903\18362.1.190318-1202.19H1_RELEASE_CLIENTMULTI_X64FRE_EN-US.iso" -WindowsApps "Select" -SystemApps -Capabilities -Packages -Fea
Please correct the --Win32Calc typo

2022-01-17 11:20 UTC, espanafly commented
thanks for the feedback!
I did consider that someone could remove the SecHealthUI package and at the same time choose the DormantDefender option. 
For my level of coding skills, I could see putting a pause in the script and add a warning that "You've chosen both. What do you really want to do?" 
I decided to just leave it and let the user choose both. At a code-level there isn't a conflict since SecHealthUI package removal would be the dominant outcome. 
I can see that the user might be surprised to discover that Defender is not just dormant, but actually unrecoverable (gone).
My first reaction to that is: "Too bad! RTFM!" But maybe that is harsh?

In defense of the "Too bad! RTFM!" solution. The user isn't going to get much benefit choosing DormantDefender TRUE without having read the ReadMe section and downloaded the online re-activation and Toggle scripts. In my mind, the README.md section makes it clear that choosing DormantDefender and also removing the SecHealthUI package is pointless. 

I still prefer your idea of integrating the less extreme registry and service changes performed by ToggleDefender and then including ToggleDefender in the O-O package. Your integration idea also has to figure out how to prevent a user from removing the SecHealthUI package.

'Src/Offline-Resources.psm1'
Please ignore that file change. There is no need for a folder.
'en-US/Optimize-Offline-help.xml'
I'll correct typo to and resubmit

2022-01-17 15:11 UTC, gdeliana commented
> thanks for the feedback! I did consider that someone could remove the SecHealthUI package and at the same time choose the DormantDefender option. For my level of coding skills, I could see putting a pause in the script and add a warning that "You've chosen both. What do you really want to do?" I decided to just leave it and let the user choose both. At a code-level there isn't a conflict since SecHealthUI package removal would be the dominant outcome. I can see that the user might be surprised to discover that Defender is not just dormant, but actually unrecoverable (gone). My first reaction to that is: "Too bad! RTFM!" But maybe that is harsh?
> 
> In defense of the "Too bad! RTFM!" solution. The user isn't going to get much benefit choosing DormantDefender TRUE without having read the ReadMe section and downloaded the online re-activation and Toggle scripts. In my mind, the README.md section makes it clear that choosing DormantDefender and also removing the SecHealthUI package is pointless.
> 
> I still prefer your idea of integrating the less extreme registry and service changes performed by ToggleDefender and then including ToggleDefender in the O-O package. Your integration idea also has to figure out how to prevent a user from removing the SecHealthUI package.
> 
> 'Src/Offline-Resources.psm1' Please ignore that file change. There is no need for a folder. 'en-US/Optimize-Offline-help.xml' I'll correct typo to and resubmit

Ok perfect let's leave it to the user then, no need to put extra logic. Just remove the extra path in the resources. I will integrate your PR and then add the Toggle- Defender as a called subscript of set-additional.

2022-01-17 23:18 UTC, espanafly commented
> Ok perfect let's leave it to the user then, no need to put extra logic. Just remove the extra path in the resources. I will integrate your PR and then add the Toggle- Defender as a called subscript of set-additional.
Thanks!
I cleaned up the formatting and added a "Note" paragraph the Dormant Microsoft Defender section of the README.md that, hopefully, makes it clear what happens if both control methods are applied.
I'll remove the extra path in the resources and commit that change. 
Thanks for all the work you do to keep this project alive!

2022-01-20 11:34 UTC, merged

2022-01-20 11:35 UTC, gdeliana commented
Mate i think you have shaved all the bugs ;)

2022-01-21 12:26 UTC, espanafly commented
No worries, mate!
This was my first attempt at making a parameter. I picked something easy and hopefully useful. Thank you for your help and advice and for all the effort you make to continually advance this project!